version: '3.9'

services:
  db:
    container_name: nestjs-app-template
    image: postgres:15.6
    restart: always
    ports:
      - "${DATABASE_PORT}:${DATABASE_PORT}"
    environment:
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_USER=${DATABASE_USERNAME}
      - POSTGRES_DB=${DATABASE_NAME}
    volumes:
      - ./postgres:/var/lib/postgresql/data
